# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:01:28+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Link(BaseModel):
    description: Optional[str] = Field(
        None,
        description='The description. In HTML speak: Everything between <a> and </a>.',
    )
    link: Optional[str] = Field(None, description='The URL.')
    type: Optional[str] = Field(None, description='Type of the link, e.g. "email".')


class Task(BaseModel):
    completed: Optional[str] = Field(
        None,
        description='Completion date of the task (as a RFC 3339 timestamp). This field is omitted if the task has not been completed.',
    )
    deleted: Optional[bool] = Field(
        None,
        description='Flag indicating whether the task has been deleted. The default is False.',
    )
    due: Optional[str] = Field(
        None,
        description="Due date of the task (as a RFC 3339 timestamp). Optional. The due date only records date information; the time portion of the timestamp is discarded when setting the due date. It isn't possible to read or write the time that a task is due via the API.",
    )
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    hidden: Optional[bool] = Field(
        None,
        description='Flag indicating whether the task is hidden. This is the case if the task had been marked completed when the task list was last cleared. The default is False. This field is read-only.',
    )
    id: Optional[str] = Field(None, description='Task identifier.')
    kind: Optional[str] = Field(
        None, description='Type of the resource. This is always "tasks#task".'
    )
    links: Optional[List[Link]] = Field(
        None, description='Collection of links. This collection is read-only.'
    )
    notes: Optional[str] = Field(
        None, description='Notes describing the task. Optional.'
    )
    parent: Optional[str] = Field(
        None,
        description='Parent task identifier. This field is omitted if it is a top-level task. This field is read-only. Use the "move" method to move the task under a different parent or to the top level.',
    )
    position: Optional[str] = Field(
        None,
        description='String indicating the position of the task among its sibling tasks under the same parent task or at the top level. If this string is greater than another task\'s corresponding position string according to lexicographical ordering, the task is positioned after the other task under the same parent task (or at the top level). This field is read-only. Use the "move" method to move the task to another position.',
    )
    selfLink: Optional[str] = Field(
        None,
        description='URL pointing to this task. Used to retrieve, update, or delete this task.',
    )
    status: Optional[str] = Field(
        None,
        description='Status of the task. This is either "needsAction" or "completed".',
    )
    title: Optional[str] = Field(None, description='Title of the task.')
    updated: Optional[str] = Field(
        None,
        description='Last modification time of the task (as a RFC 3339 timestamp).',
    )


class TaskList(BaseModel):
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    id: Optional[str] = Field(None, description='Task list identifier.')
    kind: Optional[str] = Field(
        None, description='Type of the resource. This is always "tasks#taskList".'
    )
    selfLink: Optional[str] = Field(
        None,
        description='URL pointing to this task list. Used to retrieve, update, or delete this task list.',
    )
    title: Optional[str] = Field(None, description='Title of the task list.')
    updated: Optional[str] = Field(
        None,
        description='Last modification time of the task list (as a RFC 3339 timestamp).',
    )


class TaskLists(BaseModel):
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    items: Optional[List[TaskList]] = Field(
        None, description='Collection of task lists.'
    )
    kind: Optional[str] = Field(
        None, description='Type of the resource. This is always "tasks#taskLists".'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token that can be used to request the next page of this result.',
    )


class Tasks(BaseModel):
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    items: Optional[List[Task]] = Field(None, description='Collection of tasks.')
    kind: Optional[str] = Field(
        None, description='Type of the resource. This is always "tasks#tasks".'
    )
    nextPageToken: Optional[str] = Field(
        None, description='Token used to access the next page of this result.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'
